name: Conda Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  conda-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.10"

    - name: Install conda-build and boa
      shell: bash -l {0}
      run: conda install -n base -c conda-forge conda-build boa

    - name: Build Conda Package
      shell: bash -l {0}
      run: conda mambabuild conda-recipe/
