name: Conda Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  conda-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: "latest"
        auto-activate-base: true
        activate-environment: ""

    - name: Install conda-build and boa
      shell: bash -l {0}
      run: conda install -y conda-build boa -c conda-forge

    - name: Build Conda Package
      shell: bash -l {0}
      run: conda mambabuild conda-recipe/
